SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.sales * B.PRICE) as TOTAL_SALES
FROM Book as B, AUTHOR as A, BOOK_SALES as BS
where B.BOOK_ID = BS.BOOK_ID
AND A.AUTHOR_ID = B.AUTHOR_ID
AND SALES_DATE like "2022-01%"
GROUP BY B.CATEGORY, A.AUTHOR_NAME
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC